/*
 * Object Storage
 *
 * REST API OpenAPI documentation for the Object Storage
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using storage.Model;
using storage.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace storage.Test.Model
{
    /// <summary>
    ///  Class for testing BucketObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BucketObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BucketObject
        //private BucketObject instance;

        public BucketObjectTests()
        {
            // TODO uncomment below to create an instance of BucketObject
            //instance = new BucketObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BucketObject
        /// </summary>
        [Fact]
        public void BucketObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" BucketObject
            //Assert.IsType<BucketObject>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Fact]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Etag'
        /// </summary>
        [Fact]
        public void EtagTest()
        {
            // TODO unit test for the property 'Etag'
        }
    }
}
