/*
 * Digital Certificates API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using digital_certificates.Client;
using digital_certificates.Model;

namespace digital_certificates.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUpdateDigitalCertificateApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Change only select settings of your digital certificate or CSR.
        /// </summary>
        /// <exception cref="digital_certificates.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="digitalCertificateId">ID of certificate to update</param>
        /// <param name="updateDigitalCertificateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DC200</returns>
        DC200 UpdateDigitalCertificate(int digitalCertificateId, UpdateDigitalCertificateRequest updateDigitalCertificateRequest, int operationIndex = 0);

        /// <summary>
        /// Change only select settings of your digital certificate or CSR.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="digital_certificates.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="digitalCertificateId">ID of certificate to update</param>
        /// <param name="updateDigitalCertificateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DC200</returns>
        ApiResponse<DC200> UpdateDigitalCertificateWithHttpInfo(int digitalCertificateId, UpdateDigitalCertificateRequest updateDigitalCertificateRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUpdateDigitalCertificateApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Change only select settings of your digital certificate or CSR.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="digital_certificates.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="digitalCertificateId">ID of certificate to update</param>
        /// <param name="updateDigitalCertificateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DC200</returns>
        System.Threading.Tasks.Task<DC200> UpdateDigitalCertificateAsync(int digitalCertificateId, UpdateDigitalCertificateRequest updateDigitalCertificateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Change only select settings of your digital certificate or CSR.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="digital_certificates.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="digitalCertificateId">ID of certificate to update</param>
        /// <param name="updateDigitalCertificateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DC200)</returns>
        System.Threading.Tasks.Task<ApiResponse<DC200>> UpdateDigitalCertificateWithHttpInfoAsync(int digitalCertificateId, UpdateDigitalCertificateRequest updateDigitalCertificateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUpdateDigitalCertificateApi : IUpdateDigitalCertificateApiSync, IUpdateDigitalCertificateApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UpdateDigitalCertificateApi : IUpdateDigitalCertificateApi
    {
        private digital_certificates.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateDigitalCertificateApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UpdateDigitalCertificateApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateDigitalCertificateApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UpdateDigitalCertificateApi(string basePath)
        {
            this.Configuration = digital_certificates.Client.Configuration.MergeConfigurations(
                digital_certificates.Client.GlobalConfiguration.Instance,
                new digital_certificates.Client.Configuration { BasePath = basePath }
            );
            this.Client = new digital_certificates.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new digital_certificates.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = digital_certificates.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateDigitalCertificateApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UpdateDigitalCertificateApi(digital_certificates.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = digital_certificates.Client.Configuration.MergeConfigurations(
                digital_certificates.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new digital_certificates.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new digital_certificates.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = digital_certificates.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateDigitalCertificateApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public UpdateDigitalCertificateApi(digital_certificates.Client.ISynchronousClient client, digital_certificates.Client.IAsynchronousClient asyncClient, digital_certificates.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = digital_certificates.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public digital_certificates.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public digital_certificates.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public digital_certificates.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public digital_certificates.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Change only select settings of your digital certificate or CSR. 
        /// </summary>
        /// <exception cref="digital_certificates.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="digitalCertificateId">ID of certificate to update</param>
        /// <param name="updateDigitalCertificateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DC200</returns>
        public DC200 UpdateDigitalCertificate(int digitalCertificateId, UpdateDigitalCertificateRequest updateDigitalCertificateRequest, int operationIndex = 0)
        {
            digital_certificates.Client.ApiResponse<DC200> localVarResponse = UpdateDigitalCertificateWithHttpInfo(digitalCertificateId, updateDigitalCertificateRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Change only select settings of your digital certificate or CSR. 
        /// </summary>
        /// <exception cref="digital_certificates.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="digitalCertificateId">ID of certificate to update</param>
        /// <param name="updateDigitalCertificateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DC200</returns>
        public digital_certificates.Client.ApiResponse<DC200> UpdateDigitalCertificateWithHttpInfo(int digitalCertificateId, UpdateDigitalCertificateRequest updateDigitalCertificateRequest, int operationIndex = 0)
        {
            // verify the required parameter 'updateDigitalCertificateRequest' is set
            if (updateDigitalCertificateRequest == null)
            {
                throw new digital_certificates.Client.ApiException(400, "Missing required parameter 'updateDigitalCertificateRequest' when calling UpdateDigitalCertificateApi->UpdateDigitalCertificate");
            }

            digital_certificates.Client.RequestOptions localVarRequestOptions = new digital_certificates.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json; version=3"
            };

            var localVarContentType = digital_certificates.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = digital_certificates.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("digital_certificate_id", digital_certificates.Client.ClientUtils.ParameterToString(digitalCertificateId)); // path parameter
            localVarRequestOptions.Data = updateDigitalCertificateRequest;

            localVarRequestOptions.Operation = "UpdateDigitalCertificateApi.UpdateDigitalCertificate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<DC200>("/digital_certificates/{digital_certificate_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateDigitalCertificate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Change only select settings of your digital certificate or CSR. 
        /// </summary>
        /// <exception cref="digital_certificates.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="digitalCertificateId">ID of certificate to update</param>
        /// <param name="updateDigitalCertificateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DC200</returns>
        public async System.Threading.Tasks.Task<DC200> UpdateDigitalCertificateAsync(int digitalCertificateId, UpdateDigitalCertificateRequest updateDigitalCertificateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            digital_certificates.Client.ApiResponse<DC200> localVarResponse = await UpdateDigitalCertificateWithHttpInfoAsync(digitalCertificateId, updateDigitalCertificateRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Change only select settings of your digital certificate or CSR. 
        /// </summary>
        /// <exception cref="digital_certificates.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="digitalCertificateId">ID of certificate to update</param>
        /// <param name="updateDigitalCertificateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DC200)</returns>
        public async System.Threading.Tasks.Task<digital_certificates.Client.ApiResponse<DC200>> UpdateDigitalCertificateWithHttpInfoAsync(int digitalCertificateId, UpdateDigitalCertificateRequest updateDigitalCertificateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'updateDigitalCertificateRequest' is set
            if (updateDigitalCertificateRequest == null)
            {
                throw new digital_certificates.Client.ApiException(400, "Missing required parameter 'updateDigitalCertificateRequest' when calling UpdateDigitalCertificateApi->UpdateDigitalCertificate");
            }


            digital_certificates.Client.RequestOptions localVarRequestOptions = new digital_certificates.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json; version=3"
            };

            var localVarContentType = digital_certificates.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = digital_certificates.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("digital_certificate_id", digital_certificates.Client.ClientUtils.ParameterToString(digitalCertificateId)); // path parameter
            localVarRequestOptions.Data = updateDigitalCertificateRequest;

            localVarRequestOptions.Operation = "UpdateDigitalCertificateApi.UpdateDigitalCertificate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<DC200>("/digital_certificates/{digital_certificate_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateDigitalCertificate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
