/*
 * Digital Certificates API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using digital_certificates.Model;
using digital_certificates.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace digital_certificates.Test.Model
{
    /// <summary>
    ///  Class for testing DC201
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DC201Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DC201
        //private DC201 instance;

        public DC201Tests()
        {
            // TODO uncomment below to create an instance of DC201
            //instance = new DC201();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DC201
        /// </summary>
        [Fact]
        public void DC201InstanceTest()
        {
            // TODO uncomment below to test "IsType" DC201
            //Assert.IsType<DC201>(instance);
        }


        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'SchemaVersion'
        /// </summary>
        [Fact]
        public void SchemaVersionTest()
        {
            // TODO unit test for the property 'SchemaVersion'
        }

    }

}
