/*
 * Edgenode API
 *
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using edgenode.Model;
using edgenode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace edgenode.Test.Model
{
    /// <summary>
    ///  Class for testing EdgeNodeModules
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EdgeNodeModulesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EdgeNodeModules
        //private EdgeNodeModules instance;

        public EdgeNodeModulesTests()
        {
            // TODO uncomment below to create an instance of EdgeNodeModules
            //instance = new EdgeNodeModules();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EdgeNodeModules
        /// </summary>
        [Fact]
        public void EdgeNodeModulesInstanceTest()
        {
            // TODO uncomment below to test "IsType" EdgeNodeModules
            //Assert.IsType<EdgeNodeModules>(instance);
        }


        /// <summary>
        /// Test the property 'AddServices'
        /// </summary>
        [Fact]
        public void AddServicesTest()
        {
            // TODO unit test for the property 'AddServices'
        }

    }

}
