/*
 * Edgenode API
 *
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using edgenode.Model;
using edgenode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace edgenode.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceBindDetailResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceBindDetailResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceBindDetailResponse
        //private ServiceBindDetailResponse instance;

        public ServiceBindDetailResponseTests()
        {
            // TODO uncomment below to create an instance of ServiceBindDetailResponse
            //instance = new ServiceBindDetailResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceBindDetailResponse
        /// </summary>
        [Fact]
        public void ServiceBindDetailResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceBindDetailResponse
            //Assert.IsType<ServiceBindDetailResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ServiceId'
        /// </summary>
        [Fact]
        public void ServiceIdTest()
        {
            // TODO unit test for the property 'ServiceId'
        }
        /// <summary>
        /// Test the property 'ServiceName'
        /// </summary>
        [Fact]
        public void ServiceNameTest()
        {
            // TODO unit test for the property 'ServiceName'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }

    }

}
