/*
 * Edgenode API
 *
 * Azion Orchestration
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using edgenode.Model;
using edgenode.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace edgenode.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateEdgeNodeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateEdgeNodeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateEdgeNodeResponse
        //private UpdateEdgeNodeResponse instance;

        public UpdateEdgeNodeResponseTests()
        {
            // TODO uncomment below to create an instance of UpdateEdgeNodeResponse
            //instance = new UpdateEdgeNodeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateEdgeNodeResponse
        /// </summary>
        [Fact]
        public void UpdateEdgeNodeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateEdgeNodeResponse
            //Assert.IsType<UpdateEdgeNodeResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Fact]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
