/*
 * Edge Functions Instances API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = edgefunctionsinstance_edgefirewall.Client.OpenAPIDateConverter;

namespace edgefunctionsinstance_edgefirewall.Model
{
    /// <summary>
    /// EdgeFunctionsInstance
    /// </summary>
    [DataContract(Name = "EdgeFunctionsInstance")]
    public partial class EdgeFunctionsInstance : IEquatable<EdgeFunctionsInstance>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdgeFunctionsInstance" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="lastEditor">lastEditor.</param>
        /// <param name="lastModified">lastModified.</param>
        /// <param name="jsonArgs">jsonArgs.</param>
        /// <param name="edgeFunction">edgeFunction.</param>
        public EdgeFunctionsInstance(long id = default(long), string name = default(string), string lastEditor = default(string), string lastModified = default(string), Object jsonArgs = default(Object), long edgeFunction = default(long))
        {
            this.Id = id;
            this.Name = name;
            this.LastEditor = lastEditor;
            this.LastModified = lastModified;
            this.JsonArgs = jsonArgs;
            this.EdgeFunction = edgeFunction;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets LastEditor
        /// </summary>
        [DataMember(Name = "last_editor", EmitDefaultValue = false)]
        public string LastEditor { get; set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name = "last_modified", EmitDefaultValue = false)]
        public string LastModified { get; set; }

        /// <summary>
        /// Gets or Sets JsonArgs
        /// </summary>
        [DataMember(Name = "json_args", EmitDefaultValue = true)]
        public Object JsonArgs { get; set; }

        /// <summary>
        /// Gets or Sets EdgeFunction
        /// </summary>
        [DataMember(Name = "edge_function", EmitDefaultValue = false)]
        public long EdgeFunction { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EdgeFunctionsInstance {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  LastEditor: ").Append(LastEditor).Append("\n");
            sb.Append("  LastModified: ").Append(LastModified).Append("\n");
            sb.Append("  JsonArgs: ").Append(JsonArgs).Append("\n");
            sb.Append("  EdgeFunction: ").Append(EdgeFunction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EdgeFunctionsInstance);
        }

        /// <summary>
        /// Returns true if EdgeFunctionsInstance instances are equal
        /// </summary>
        /// <param name="input">Instance of EdgeFunctionsInstance to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdgeFunctionsInstance input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.LastEditor == input.LastEditor ||
                    (this.LastEditor != null &&
                    this.LastEditor.Equals(input.LastEditor))
                ) && 
                (
                    this.LastModified == input.LastModified ||
                    (this.LastModified != null &&
                    this.LastModified.Equals(input.LastModified))
                ) && 
                (
                    this.JsonArgs == input.JsonArgs ||
                    (this.JsonArgs != null &&
                    this.JsonArgs.Equals(input.JsonArgs))
                ) && 
                (
                    this.EdgeFunction == input.EdgeFunction ||
                    this.EdgeFunction.Equals(input.EdgeFunction)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.LastEditor != null)
                {
                    hashCode = (hashCode * 59) + this.LastEditor.GetHashCode();
                }
                if (this.LastModified != null)
                {
                    hashCode = (hashCode * 59) + this.LastModified.GetHashCode();
                }
                if (this.JsonArgs != null)
                {
                    hashCode = (hashCode * 59) + this.JsonArgs.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.EdgeFunction.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
