/*
 * Web Application Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using waf.Model;
using waf.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace waf.Test.Model
{
    /// <summary>
    ///  Class for testing WAFEvents200ResultsInnerTop10CountriesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WAFEvents200ResultsInnerTop10CountriesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WAFEvents200ResultsInnerTop10CountriesInner
        //private WAFEvents200ResultsInnerTop10CountriesInner instance;

        public WAFEvents200ResultsInnerTop10CountriesInnerTests()
        {
            // TODO uncomment below to create an instance of WAFEvents200ResultsInnerTop10CountriesInner
            //instance = new WAFEvents200ResultsInnerTop10CountriesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WAFEvents200ResultsInnerTop10CountriesInner
        /// </summary>
        [Fact]
        public void WAFEvents200ResultsInnerTop10CountriesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" WAFEvents200ResultsInnerTop10CountriesInner
            //Assert.IsType<WAFEvents200ResultsInnerTop10CountriesInner>(instance);
        }
    }
}
