/*
 * Web Application Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using waf.Model;
using waf.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace waf.Test.Model
{
    /// <summary>
    ///  Class for testing WAFEvents200ResultsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WAFEvents200ResultsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WAFEvents200ResultsInner
        //private WAFEvents200ResultsInner instance;

        public WAFEvents200ResultsInnerTests()
        {
            // TODO uncomment below to create an instance of WAFEvents200ResultsInner
            //instance = new WAFEvents200ResultsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WAFEvents200ResultsInner
        /// </summary>
        [Fact]
        public void WAFEvents200ResultsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" WAFEvents200ResultsInner
            //Assert.IsType<WAFEvents200ResultsInner>(instance);
        }

        /// <summary>
        /// Test the property 'CountryCount'
        /// </summary>
        [Fact]
        public void CountryCountTest()
        {
            // TODO unit test for the property 'CountryCount'
        }

        /// <summary>
        /// Test the property 'Top10Countries'
        /// </summary>
        [Fact]
        public void Top10CountriesTest()
        {
            // TODO unit test for the property 'Top10Countries'
        }

        /// <summary>
        /// Test the property 'Top10Ips'
        /// </summary>
        [Fact]
        public void Top10IpsTest()
        {
            // TODO unit test for the property 'Top10Ips'
        }

        /// <summary>
        /// Test the property 'HitCount'
        /// </summary>
        [Fact]
        public void HitCountTest()
        {
            // TODO unit test for the property 'HitCount'
        }

        /// <summary>
        /// Test the property 'RuleId'
        /// </summary>
        [Fact]
        public void RuleIdTest()
        {
            // TODO unit test for the property 'RuleId'
        }

        /// <summary>
        /// Test the property 'IpCount'
        /// </summary>
        [Fact]
        public void IpCountTest()
        {
            // TODO unit test for the property 'IpCount'
        }

        /// <summary>
        /// Test the property 'MatchZone'
        /// </summary>
        [Fact]
        public void MatchZoneTest()
        {
            // TODO unit test for the property 'MatchZone'
        }

        /// <summary>
        /// Test the property 'PathCount'
        /// </summary>
        [Fact]
        public void PathCountTest()
        {
            // TODO unit test for the property 'PathCount'
        }

        /// <summary>
        /// Test the property 'MatchesOn'
        /// </summary>
        [Fact]
        public void MatchesOnTest()
        {
            // TODO unit test for the property 'MatchesOn'
        }

        /// <summary>
        /// Test the property 'RuleDescription'
        /// </summary>
        [Fact]
        public void RuleDescriptionTest()
        {
            // TODO unit test for the property 'RuleDescription'
        }
    }
}
