/*
 * Edge Application API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using edgeapplications.Model;
using edgeapplications.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace edgeapplications.Test.Model
{
    /// <summary>
    ///  Class for testing RulesEngineBehaviorObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RulesEngineBehaviorObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RulesEngineBehaviorObject
        //private RulesEngineBehaviorObject instance;

        public RulesEngineBehaviorObjectTests()
        {
            // TODO uncomment below to create an instance of RulesEngineBehaviorObject
            //instance = new RulesEngineBehaviorObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RulesEngineBehaviorObject
        /// </summary>
        [Fact]
        public void RulesEngineBehaviorObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" RulesEngineBehaviorObject
            //Assert.IsType<RulesEngineBehaviorObject>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }
    }
}
