/*
 * Edge Firewall API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using edgefirewall.Model;
using edgefirewall.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace edgefirewall.Test.Model
{
    /// <summary>
    ///  Class for testing SetCustomResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetCustomResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetCustomResponse
        //private SetCustomResponse instance;

        public SetCustomResponseTests()
        {
            // TODO uncomment below to create an instance of SetCustomResponse
            //instance = new SetCustomResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetCustomResponse
        /// </summary>
        [Fact]
        public void SetCustomResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetCustomResponse
            //Assert.IsType<SetCustomResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Argument'
        /// </summary>
        [Fact]
        public void ArgumentTest()
        {
            // TODO unit test for the property 'Argument'
        }
    }
}
