/*
 * Data Streaming - OpenAPI
 *
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using data_streaming.Client;
using data_streaming.Api;
// uncomment below to import models
//using data_streaming.Model;

namespace data_streaming.Test.Api
{
    /// <summary>
    ///  Class for testing DataStreamingDomainApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DataStreamingDomainApiTests : IDisposable
    {
        private DataStreamingDomainApi instance;

        public DataStreamingDomainApiTests()
        {
            instance = new DataStreamingDomainApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataStreamingDomainApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DataStreamingDomainApi
            //Assert.IsType<DataStreamingDomainApi>(instance);
        }

        /// <summary>
        /// Test ListDataStreaming
        /// </summary>
        [Fact]
        public void ListDataStreamingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //long? streamingId = null;
            //bool? selected = null;
            //var response = instance.ListDataStreaming(name, streamingId, selected);
            //Assert.IsType<DataStreamingsDomainResponse>(response);
        }
    }
}
