// <auto-generated>
/*
 * Edge Application API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using edgeapplications.Client;

namespace edgeapplications.Model
{
    /// <summary>
    /// ApplicationCachePatchRequest
    /// </summary>
    public partial class ApplicationCachePatchRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationCachePatchRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="browserCacheSettings">browserCacheSettings</param>
        /// <param name="browserCacheSettingsMaximumTtl">browserCacheSettingsMaximumTtl</param>
        /// <param name="cdnCacheSettings">cdnCacheSettings</param>
        /// <param name="adaptiveDeliveryAction">adaptiveDeliveryAction</param>
        /// <param name="enableCachingForOptions">enableCachingForOptions</param>
        /// <param name="cdnCacheSettingsMaximumTtl">cdnCacheSettingsMaximumTtl</param>
        /// <param name="cacheByQueryString">cacheByQueryString</param>
        /// <param name="queryStringFields">queryStringFields</param>
        /// <param name="enableQueryStringSort">enableQueryStringSort</param>
        /// <param name="cacheByCookies">cacheByCookies</param>
        /// <param name="cookieNames">cookieNames</param>
        /// <param name="enableCachingForPost">enableCachingForPost</param>
        /// <param name="l2CachingEnabled">l2CachingEnabled</param>
        /// <param name="isSliceConfigurationEnabled">isSliceConfigurationEnabled</param>
        /// <param name="isSliceEdgeCachingEnabled">isSliceEdgeCachingEnabled</param>
        /// <param name="isSliceL2CachingEnabled">isSliceL2CachingEnabled</param>
        /// <param name="sliceConfigurationRange">sliceConfigurationRange</param>
        [JsonConstructor]
        public ApplicationCachePatchRequest(Option<string?> name = default, Option<string?> browserCacheSettings = default, Option<long?> browserCacheSettingsMaximumTtl = default, Option<string?> cdnCacheSettings = default, Option<string?> adaptiveDeliveryAction = default, Option<bool?> enableCachingForOptions = default, Option<long?> cdnCacheSettingsMaximumTtl = default, Option<string?> cacheByQueryString = default, Option<List<string>?> queryStringFields = default, Option<bool?> enableQueryStringSort = default, Option<string?> cacheByCookies = default, Option<List<string>?> cookieNames = default, Option<bool?> enableCachingForPost = default, Option<bool?> l2CachingEnabled = default, Option<bool?> isSliceConfigurationEnabled = default, Option<bool?> isSliceEdgeCachingEnabled = default, Option<bool?> isSliceL2CachingEnabled = default, Option<long?> sliceConfigurationRange = default)
        {
            NameOption = name;
            BrowserCacheSettingsOption = browserCacheSettings;
            BrowserCacheSettingsMaximumTtlOption = browserCacheSettingsMaximumTtl;
            CdnCacheSettingsOption = cdnCacheSettings;
            AdaptiveDeliveryActionOption = adaptiveDeliveryAction;
            EnableCachingForOptionsOption = enableCachingForOptions;
            CdnCacheSettingsMaximumTtlOption = cdnCacheSettingsMaximumTtl;
            CacheByQueryStringOption = cacheByQueryString;
            QueryStringFieldsOption = queryStringFields;
            EnableQueryStringSortOption = enableQueryStringSort;
            CacheByCookiesOption = cacheByCookies;
            CookieNamesOption = cookieNames;
            EnableCachingForPostOption = enableCachingForPost;
            L2CachingEnabledOption = l2CachingEnabled;
            IsSliceConfigurationEnabledOption = isSliceConfigurationEnabled;
            IsSliceEdgeCachingEnabledOption = isSliceEdgeCachingEnabled;
            IsSliceL2CachingEnabledOption = isSliceL2CachingEnabled;
            SliceConfigurationRangeOption = sliceConfigurationRange;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of BrowserCacheSettings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BrowserCacheSettingsOption { get; private set; }

        /// <summary>
        /// Gets or Sets BrowserCacheSettings
        /// </summary>
        [JsonPropertyName("browser_cache_settings")]
        public string? BrowserCacheSettings { get { return this.BrowserCacheSettingsOption; } set { this.BrowserCacheSettingsOption = new(value); } }

        /// <summary>
        /// Used to track the state of BrowserCacheSettingsMaximumTtl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> BrowserCacheSettingsMaximumTtlOption { get; private set; }

        /// <summary>
        /// Gets or Sets BrowserCacheSettingsMaximumTtl
        /// </summary>
        [JsonPropertyName("browser_cache_settings_maximum_ttl")]
        public long? BrowserCacheSettingsMaximumTtl { get { return this.BrowserCacheSettingsMaximumTtlOption; } set { this.BrowserCacheSettingsMaximumTtlOption = new(value); } }

        /// <summary>
        /// Used to track the state of CdnCacheSettings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CdnCacheSettingsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CdnCacheSettings
        /// </summary>
        [JsonPropertyName("cdn_cache_settings")]
        public string? CdnCacheSettings { get { return this.CdnCacheSettingsOption; } set { this.CdnCacheSettingsOption = new(value); } }

        /// <summary>
        /// Used to track the state of AdaptiveDeliveryAction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AdaptiveDeliveryActionOption { get; private set; }

        /// <summary>
        /// Gets or Sets AdaptiveDeliveryAction
        /// </summary>
        [JsonPropertyName("adaptive_delivery_action")]
        public string? AdaptiveDeliveryAction { get { return this.AdaptiveDeliveryActionOption; } set { this.AdaptiveDeliveryActionOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnableCachingForOptions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableCachingForOptionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableCachingForOptions
        /// </summary>
        [JsonPropertyName("enable_caching_for_options")]
        public bool? EnableCachingForOptions { get { return this.EnableCachingForOptionsOption; } set { this.EnableCachingForOptionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of CdnCacheSettingsMaximumTtl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> CdnCacheSettingsMaximumTtlOption { get; private set; }

        /// <summary>
        /// Gets or Sets CdnCacheSettingsMaximumTtl
        /// </summary>
        [JsonPropertyName("cdn_cache_settings_maximum_ttl")]
        public long? CdnCacheSettingsMaximumTtl { get { return this.CdnCacheSettingsMaximumTtlOption; } set { this.CdnCacheSettingsMaximumTtlOption = new(value); } }

        /// <summary>
        /// Used to track the state of CacheByQueryString
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CacheByQueryStringOption { get; private set; }

        /// <summary>
        /// Gets or Sets CacheByQueryString
        /// </summary>
        [JsonPropertyName("cache_by_query_string")]
        public string? CacheByQueryString { get { return this.CacheByQueryStringOption; } set { this.CacheByQueryStringOption = new(value); } }

        /// <summary>
        /// Used to track the state of QueryStringFields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> QueryStringFieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets QueryStringFields
        /// </summary>
        [JsonPropertyName("query_string_fields")]
        public List<string>? QueryStringFields { get { return this.QueryStringFieldsOption; } set { this.QueryStringFieldsOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnableQueryStringSort
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableQueryStringSortOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableQueryStringSort
        /// </summary>
        [JsonPropertyName("enable_query_string_sort")]
        public bool? EnableQueryStringSort { get { return this.EnableQueryStringSortOption; } set { this.EnableQueryStringSortOption = new(value); } }

        /// <summary>
        /// Used to track the state of CacheByCookies
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CacheByCookiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets CacheByCookies
        /// </summary>
        [JsonPropertyName("cache_by_cookies")]
        public string? CacheByCookies { get { return this.CacheByCookiesOption; } set { this.CacheByCookiesOption = new(value); } }

        /// <summary>
        /// Used to track the state of CookieNames
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> CookieNamesOption { get; private set; }

        /// <summary>
        /// Gets or Sets CookieNames
        /// </summary>
        [JsonPropertyName("cookie_names")]
        public List<string>? CookieNames { get { return this.CookieNamesOption; } set { this.CookieNamesOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnableCachingForPost
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableCachingForPostOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnableCachingForPost
        /// </summary>
        [JsonPropertyName("enable_caching_for_post")]
        public bool? EnableCachingForPost { get { return this.EnableCachingForPostOption; } set { this.EnableCachingForPostOption = new(value); } }

        /// <summary>
        /// Used to track the state of L2CachingEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> L2CachingEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets L2CachingEnabled
        /// </summary>
        [JsonPropertyName("l2_caching_enabled")]
        public bool? L2CachingEnabled { get { return this.L2CachingEnabledOption; } set { this.L2CachingEnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsSliceConfigurationEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsSliceConfigurationEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsSliceConfigurationEnabled
        /// </summary>
        [JsonPropertyName("is_slice_configuration_enabled")]
        public bool? IsSliceConfigurationEnabled { get { return this.IsSliceConfigurationEnabledOption; } set { this.IsSliceConfigurationEnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsSliceEdgeCachingEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsSliceEdgeCachingEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsSliceEdgeCachingEnabled
        /// </summary>
        [JsonPropertyName("is_slice_edge_caching_enabled")]
        public bool? IsSliceEdgeCachingEnabled { get { return this.IsSliceEdgeCachingEnabledOption; } set { this.IsSliceEdgeCachingEnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsSliceL2CachingEnabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsSliceL2CachingEnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsSliceL2CachingEnabled
        /// </summary>
        [JsonPropertyName("is_slice_l2_caching_enabled")]
        public bool? IsSliceL2CachingEnabled { get { return this.IsSliceL2CachingEnabledOption; } set { this.IsSliceL2CachingEnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of SliceConfigurationRange
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SliceConfigurationRangeOption { get; private set; }

        /// <summary>
        /// Gets or Sets SliceConfigurationRange
        /// </summary>
        [JsonPropertyName("slice_configuration_range")]
        public long? SliceConfigurationRange { get { return this.SliceConfigurationRangeOption; } set { this.SliceConfigurationRangeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApplicationCachePatchRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  BrowserCacheSettings: ").Append(BrowserCacheSettings).Append("\n");
            sb.Append("  BrowserCacheSettingsMaximumTtl: ").Append(BrowserCacheSettingsMaximumTtl).Append("\n");
            sb.Append("  CdnCacheSettings: ").Append(CdnCacheSettings).Append("\n");
            sb.Append("  AdaptiveDeliveryAction: ").Append(AdaptiveDeliveryAction).Append("\n");
            sb.Append("  EnableCachingForOptions: ").Append(EnableCachingForOptions).Append("\n");
            sb.Append("  CdnCacheSettingsMaximumTtl: ").Append(CdnCacheSettingsMaximumTtl).Append("\n");
            sb.Append("  CacheByQueryString: ").Append(CacheByQueryString).Append("\n");
            sb.Append("  QueryStringFields: ").Append(QueryStringFields).Append("\n");
            sb.Append("  EnableQueryStringSort: ").Append(EnableQueryStringSort).Append("\n");
            sb.Append("  CacheByCookies: ").Append(CacheByCookies).Append("\n");
            sb.Append("  CookieNames: ").Append(CookieNames).Append("\n");
            sb.Append("  EnableCachingForPost: ").Append(EnableCachingForPost).Append("\n");
            sb.Append("  L2CachingEnabled: ").Append(L2CachingEnabled).Append("\n");
            sb.Append("  IsSliceConfigurationEnabled: ").Append(IsSliceConfigurationEnabled).Append("\n");
            sb.Append("  IsSliceEdgeCachingEnabled: ").Append(IsSliceEdgeCachingEnabled).Append("\n");
            sb.Append("  IsSliceL2CachingEnabled: ").Append(IsSliceL2CachingEnabled).Append("\n");
            sb.Append("  SliceConfigurationRange: ").Append(SliceConfigurationRange).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApplicationCachePatchRequest" />
    /// </summary>
    public class ApplicationCachePatchRequestJsonConverter : JsonConverter<ApplicationCachePatchRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ApplicationCachePatchRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApplicationCachePatchRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> browserCacheSettings = default;
            Option<long?> browserCacheSettingsMaximumTtl = default;
            Option<string?> cdnCacheSettings = default;
            Option<string?> adaptiveDeliveryAction = default;
            Option<bool?> enableCachingForOptions = default;
            Option<long?> cdnCacheSettingsMaximumTtl = default;
            Option<string?> cacheByQueryString = default;
            Option<List<string>?> queryStringFields = default;
            Option<bool?> enableQueryStringSort = default;
            Option<string?> cacheByCookies = default;
            Option<List<string>?> cookieNames = default;
            Option<bool?> enableCachingForPost = default;
            Option<bool?> l2CachingEnabled = default;
            Option<bool?> isSliceConfigurationEnabled = default;
            Option<bool?> isSliceEdgeCachingEnabled = default;
            Option<bool?> isSliceL2CachingEnabled = default;
            Option<long?> sliceConfigurationRange = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "browser_cache_settings":
                            browserCacheSettings = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "browser_cache_settings_maximum_ttl":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                browserCacheSettingsMaximumTtl = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "cdn_cache_settings":
                            cdnCacheSettings = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "adaptive_delivery_action":
                            adaptiveDeliveryAction = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "enable_caching_for_options":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                enableCachingForOptions = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "cdn_cache_settings_maximum_ttl":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                cdnCacheSettingsMaximumTtl = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "cache_by_query_string":
                            cacheByQueryString = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "query_string_fields":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                queryStringFields = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "enable_query_string_sort":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                enableQueryStringSort = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "cache_by_cookies":
                            cacheByCookies = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "cookie_names":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                cookieNames = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "enable_caching_for_post":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                enableCachingForPost = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "l2_caching_enabled":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                l2CachingEnabled = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "is_slice_configuration_enabled":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isSliceConfigurationEnabled = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "is_slice_edge_caching_enabled":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isSliceEdgeCachingEnabled = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "is_slice_l2_caching_enabled":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isSliceL2CachingEnabled = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "slice_configuration_range":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                sliceConfigurationRange = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (browserCacheSettings.IsSet && browserCacheSettings.Value == null)
                throw new ArgumentNullException(nameof(browserCacheSettings), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (browserCacheSettingsMaximumTtl.IsSet && browserCacheSettingsMaximumTtl.Value == null)
                throw new ArgumentNullException(nameof(browserCacheSettingsMaximumTtl), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (cdnCacheSettings.IsSet && cdnCacheSettings.Value == null)
                throw new ArgumentNullException(nameof(cdnCacheSettings), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (adaptiveDeliveryAction.IsSet && adaptiveDeliveryAction.Value == null)
                throw new ArgumentNullException(nameof(adaptiveDeliveryAction), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (enableCachingForOptions.IsSet && enableCachingForOptions.Value == null)
                throw new ArgumentNullException(nameof(enableCachingForOptions), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (cdnCacheSettingsMaximumTtl.IsSet && cdnCacheSettingsMaximumTtl.Value == null)
                throw new ArgumentNullException(nameof(cdnCacheSettingsMaximumTtl), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (cacheByQueryString.IsSet && cacheByQueryString.Value == null)
                throw new ArgumentNullException(nameof(cacheByQueryString), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (queryStringFields.IsSet && queryStringFields.Value == null)
                throw new ArgumentNullException(nameof(queryStringFields), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (enableQueryStringSort.IsSet && enableQueryStringSort.Value == null)
                throw new ArgumentNullException(nameof(enableQueryStringSort), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (cacheByCookies.IsSet && cacheByCookies.Value == null)
                throw new ArgumentNullException(nameof(cacheByCookies), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (cookieNames.IsSet && cookieNames.Value == null)
                throw new ArgumentNullException(nameof(cookieNames), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (enableCachingForPost.IsSet && enableCachingForPost.Value == null)
                throw new ArgumentNullException(nameof(enableCachingForPost), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (l2CachingEnabled.IsSet && l2CachingEnabled.Value == null)
                throw new ArgumentNullException(nameof(l2CachingEnabled), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (isSliceConfigurationEnabled.IsSet && isSliceConfigurationEnabled.Value == null)
                throw new ArgumentNullException(nameof(isSliceConfigurationEnabled), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (isSliceEdgeCachingEnabled.IsSet && isSliceEdgeCachingEnabled.Value == null)
                throw new ArgumentNullException(nameof(isSliceEdgeCachingEnabled), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (isSliceL2CachingEnabled.IsSet && isSliceL2CachingEnabled.Value == null)
                throw new ArgumentNullException(nameof(isSliceL2CachingEnabled), "Property is not nullable for class ApplicationCachePatchRequest.");

            if (sliceConfigurationRange.IsSet && sliceConfigurationRange.Value == null)
                throw new ArgumentNullException(nameof(sliceConfigurationRange), "Property is not nullable for class ApplicationCachePatchRequest.");

            return new ApplicationCachePatchRequest(name, browserCacheSettings, browserCacheSettingsMaximumTtl, cdnCacheSettings, adaptiveDeliveryAction, enableCachingForOptions, cdnCacheSettingsMaximumTtl, cacheByQueryString, queryStringFields, enableQueryStringSort, cacheByCookies, cookieNames, enableCachingForPost, l2CachingEnabled, isSliceConfigurationEnabled, isSliceEdgeCachingEnabled, isSliceL2CachingEnabled, sliceConfigurationRange);
        }

        /// <summary>
        /// Serializes a <see cref="ApplicationCachePatchRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="applicationCachePatchRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApplicationCachePatchRequest applicationCachePatchRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, applicationCachePatchRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApplicationCachePatchRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="applicationCachePatchRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApplicationCachePatchRequest applicationCachePatchRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (applicationCachePatchRequest.NameOption.IsSet && applicationCachePatchRequest.Name == null)
                throw new ArgumentNullException(nameof(applicationCachePatchRequest.Name), "Property is required for class ApplicationCachePatchRequest.");

            if (applicationCachePatchRequest.BrowserCacheSettingsOption.IsSet && applicationCachePatchRequest.BrowserCacheSettings == null)
                throw new ArgumentNullException(nameof(applicationCachePatchRequest.BrowserCacheSettings), "Property is required for class ApplicationCachePatchRequest.");

            if (applicationCachePatchRequest.CdnCacheSettingsOption.IsSet && applicationCachePatchRequest.CdnCacheSettings == null)
                throw new ArgumentNullException(nameof(applicationCachePatchRequest.CdnCacheSettings), "Property is required for class ApplicationCachePatchRequest.");

            if (applicationCachePatchRequest.AdaptiveDeliveryActionOption.IsSet && applicationCachePatchRequest.AdaptiveDeliveryAction == null)
                throw new ArgumentNullException(nameof(applicationCachePatchRequest.AdaptiveDeliveryAction), "Property is required for class ApplicationCachePatchRequest.");

            if (applicationCachePatchRequest.CacheByQueryStringOption.IsSet && applicationCachePatchRequest.CacheByQueryString == null)
                throw new ArgumentNullException(nameof(applicationCachePatchRequest.CacheByQueryString), "Property is required for class ApplicationCachePatchRequest.");

            if (applicationCachePatchRequest.QueryStringFieldsOption.IsSet && applicationCachePatchRequest.QueryStringFields == null)
                throw new ArgumentNullException(nameof(applicationCachePatchRequest.QueryStringFields), "Property is required for class ApplicationCachePatchRequest.");

            if (applicationCachePatchRequest.CacheByCookiesOption.IsSet && applicationCachePatchRequest.CacheByCookies == null)
                throw new ArgumentNullException(nameof(applicationCachePatchRequest.CacheByCookies), "Property is required for class ApplicationCachePatchRequest.");

            if (applicationCachePatchRequest.CookieNamesOption.IsSet && applicationCachePatchRequest.CookieNames == null)
                throw new ArgumentNullException(nameof(applicationCachePatchRequest.CookieNames), "Property is required for class ApplicationCachePatchRequest.");

            if (applicationCachePatchRequest.NameOption.IsSet)
                writer.WriteString("name", applicationCachePatchRequest.Name);

            if (applicationCachePatchRequest.BrowserCacheSettingsOption.IsSet)
                writer.WriteString("browser_cache_settings", applicationCachePatchRequest.BrowserCacheSettings);

            if (applicationCachePatchRequest.BrowserCacheSettingsMaximumTtlOption.IsSet)
                writer.WriteNumber("browser_cache_settings_maximum_ttl", applicationCachePatchRequest.BrowserCacheSettingsMaximumTtlOption.Value!.Value);

            if (applicationCachePatchRequest.CdnCacheSettingsOption.IsSet)
                writer.WriteString("cdn_cache_settings", applicationCachePatchRequest.CdnCacheSettings);

            if (applicationCachePatchRequest.AdaptiveDeliveryActionOption.IsSet)
                writer.WriteString("adaptive_delivery_action", applicationCachePatchRequest.AdaptiveDeliveryAction);

            if (applicationCachePatchRequest.EnableCachingForOptionsOption.IsSet)
                writer.WriteBoolean("enable_caching_for_options", applicationCachePatchRequest.EnableCachingForOptionsOption.Value!.Value);

            if (applicationCachePatchRequest.CdnCacheSettingsMaximumTtlOption.IsSet)
                writer.WriteNumber("cdn_cache_settings_maximum_ttl", applicationCachePatchRequest.CdnCacheSettingsMaximumTtlOption.Value!.Value);

            if (applicationCachePatchRequest.CacheByQueryStringOption.IsSet)
                writer.WriteString("cache_by_query_string", applicationCachePatchRequest.CacheByQueryString);

            if (applicationCachePatchRequest.QueryStringFieldsOption.IsSet)
            {
                writer.WritePropertyName("query_string_fields");
                JsonSerializer.Serialize(writer, applicationCachePatchRequest.QueryStringFields, jsonSerializerOptions);
            }
            if (applicationCachePatchRequest.EnableQueryStringSortOption.IsSet)
                writer.WriteBoolean("enable_query_string_sort", applicationCachePatchRequest.EnableQueryStringSortOption.Value!.Value);

            if (applicationCachePatchRequest.CacheByCookiesOption.IsSet)
                writer.WriteString("cache_by_cookies", applicationCachePatchRequest.CacheByCookies);

            if (applicationCachePatchRequest.CookieNamesOption.IsSet)
            {
                writer.WritePropertyName("cookie_names");
                JsonSerializer.Serialize(writer, applicationCachePatchRequest.CookieNames, jsonSerializerOptions);
            }
            if (applicationCachePatchRequest.EnableCachingForPostOption.IsSet)
                writer.WriteBoolean("enable_caching_for_post", applicationCachePatchRequest.EnableCachingForPostOption.Value!.Value);

            if (applicationCachePatchRequest.L2CachingEnabledOption.IsSet)
                writer.WriteBoolean("l2_caching_enabled", applicationCachePatchRequest.L2CachingEnabledOption.Value!.Value);

            if (applicationCachePatchRequest.IsSliceConfigurationEnabledOption.IsSet)
                writer.WriteBoolean("is_slice_configuration_enabled", applicationCachePatchRequest.IsSliceConfigurationEnabledOption.Value!.Value);

            if (applicationCachePatchRequest.IsSliceEdgeCachingEnabledOption.IsSet)
                writer.WriteBoolean("is_slice_edge_caching_enabled", applicationCachePatchRequest.IsSliceEdgeCachingEnabledOption.Value!.Value);

            if (applicationCachePatchRequest.IsSliceL2CachingEnabledOption.IsSet)
                writer.WriteBoolean("is_slice_l2_caching_enabled", applicationCachePatchRequest.IsSliceL2CachingEnabledOption.Value!.Value);

            if (applicationCachePatchRequest.SliceConfigurationRangeOption.IsSet)
                writer.WriteNumber("slice_configuration_range", applicationCachePatchRequest.SliceConfigurationRangeOption.Value!.Value);
        }
    }
}
