/*
 * Edge Application API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = edgeapplications.Client.OpenAPIDateConverter;

namespace edgeapplications.Model
{
    /// <summary>
    /// UpdateOriginsRequest
    /// </summary>
    [DataContract(Name = "UpdateOriginsRequest")]
    public partial class UpdateOriginsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOriginsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateOriginsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOriginsRequest" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="originType">originType.</param>
        /// <param name="addresses">addresses.</param>
        /// <param name="originProtocolPolicy">originProtocolPolicy.</param>
        /// <param name="hostHeader">hostHeader.</param>
        /// <param name="originPath">originPath.</param>
        /// <param name="hmacAuthentication">hmacAuthentication.</param>
        /// <param name="hmacRegionName">hmacRegionName.</param>
        /// <param name="hmacAccessKey">hmacAccessKey.</param>
        /// <param name="hmacSecretKey">hmacSecretKey.</param>
        /// <param name="bucket">bucket.</param>
        /// <param name="prefix">prefix.</param>
        public UpdateOriginsRequest(string name = default(string), string originType = default(string), List<CreateOriginsRequestAddresses> addresses = default(List<CreateOriginsRequestAddresses>), string originProtocolPolicy = default(string), string hostHeader = default(string), string originPath = default(string), bool hmacAuthentication = default(bool), string hmacRegionName = default(string), string hmacAccessKey = default(string), string hmacSecretKey = default(string), string bucket = default(string), string prefix = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for UpdateOriginsRequest and cannot be null");
            }
            this.Name = name;
            this.OriginType = originType;
            this.Addresses = addresses;
            this.OriginProtocolPolicy = originProtocolPolicy;
            this.HostHeader = hostHeader;
            this.OriginPath = originPath;
            this.HmacAuthentication = hmacAuthentication;
            this.HmacRegionName = hmacRegionName;
            this.HmacAccessKey = hmacAccessKey;
            this.HmacSecretKey = hmacSecretKey;
            this.Bucket = bucket;
            this.Prefix = prefix;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets OriginType
        /// </summary>
        [DataMember(Name = "origin_type", EmitDefaultValue = false)]
        public string OriginType { get; set; }

        /// <summary>
        /// Gets or Sets Addresses
        /// </summary>
        [DataMember(Name = "addresses", EmitDefaultValue = false)]
        public List<CreateOriginsRequestAddresses> Addresses { get; set; }

        /// <summary>
        /// Gets or Sets OriginProtocolPolicy
        /// </summary>
        [DataMember(Name = "origin_protocol_policy", EmitDefaultValue = false)]
        public string OriginProtocolPolicy { get; set; }

        /// <summary>
        /// Gets or Sets HostHeader
        /// </summary>
        [DataMember(Name = "host_header", EmitDefaultValue = false)]
        public string HostHeader { get; set; }

        /// <summary>
        /// Gets or Sets OriginPath
        /// </summary>
        [DataMember(Name = "origin_path", EmitDefaultValue = false)]
        public string OriginPath { get; set; }

        /// <summary>
        /// Gets or Sets HmacAuthentication
        /// </summary>
        [DataMember(Name = "hmac_authentication", EmitDefaultValue = true)]
        public bool HmacAuthentication { get; set; }

        /// <summary>
        /// Gets or Sets HmacRegionName
        /// </summary>
        [DataMember(Name = "hmac_region_name", EmitDefaultValue = false)]
        public string HmacRegionName { get; set; }

        /// <summary>
        /// Gets or Sets HmacAccessKey
        /// </summary>
        [DataMember(Name = "hmac_access_key", EmitDefaultValue = false)]
        public string HmacAccessKey { get; set; }

        /// <summary>
        /// Gets or Sets HmacSecretKey
        /// </summary>
        [DataMember(Name = "hmac_secret_key", EmitDefaultValue = false)]
        public string HmacSecretKey { get; set; }

        /// <summary>
        /// Gets or Sets Bucket
        /// </summary>
        [DataMember(Name = "bucket", EmitDefaultValue = false)]
        public string Bucket { get; set; }

        /// <summary>
        /// Gets or Sets Prefix
        /// </summary>
        [DataMember(Name = "prefix", EmitDefaultValue = false)]
        public string Prefix { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateOriginsRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OriginType: ").Append(OriginType).Append("\n");
            sb.Append("  Addresses: ").Append(Addresses).Append("\n");
            sb.Append("  OriginProtocolPolicy: ").Append(OriginProtocolPolicy).Append("\n");
            sb.Append("  HostHeader: ").Append(HostHeader).Append("\n");
            sb.Append("  OriginPath: ").Append(OriginPath).Append("\n");
            sb.Append("  HmacAuthentication: ").Append(HmacAuthentication).Append("\n");
            sb.Append("  HmacRegionName: ").Append(HmacRegionName).Append("\n");
            sb.Append("  HmacAccessKey: ").Append(HmacAccessKey).Append("\n");
            sb.Append("  HmacSecretKey: ").Append(HmacSecretKey).Append("\n");
            sb.Append("  Bucket: ").Append(Bucket).Append("\n");
            sb.Append("  Prefix: ").Append(Prefix).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
