/*
 * Data Streaming - OpenAPI
 *
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using data_streaming.Model;
using data_streaming.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace data_streaming.Test.Model
{
    /// <summary>
    ///  Class for testing CreateNewDataStreamingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateNewDataStreamingRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateNewDataStreamingRequest
        //private CreateNewDataStreamingRequest instance;

        public CreateNewDataStreamingRequestTests()
        {
            // TODO uncomment below to create an instance of CreateNewDataStreamingRequest
            //instance = new CreateNewDataStreamingRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateNewDataStreamingRequest
        /// </summary>
        [Fact]
        public void CreateNewDataStreamingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateNewDataStreamingRequest
            //Assert.IsType<CreateNewDataStreamingRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }
        /// <summary>
        /// Test the property 'DataSource'
        /// </summary>
        [Fact]
        public void DataSourceTest()
        {
            // TODO unit test for the property 'DataSource'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Endpoint'
        /// </summary>
        [Fact]
        public void EndpointTest()
        {
            // TODO unit test for the property 'Endpoint'
        }
        /// <summary>
        /// Test the property 'DomainsIds'
        /// </summary>
        [Fact]
        public void DomainsIdsTest()
        {
            // TODO unit test for the property 'DomainsIds'
        }
        /// <summary>
        /// Test the property 'AllDomains'
        /// </summary>
        [Fact]
        public void AllDomainsTest()
        {
            // TODO unit test for the property 'AllDomains'
        }
        /// <summary>
        /// Test the property 'SamplingPercentage'
        /// </summary>
        [Fact]
        public void SamplingPercentageTest()
        {
            // TODO unit test for the property 'SamplingPercentage'
        }
        /// <summary>
        /// Test the property 'TemplateModel'
        /// </summary>
        [Fact]
        public void TemplateModelTest()
        {
            // TODO unit test for the property 'TemplateModel'
        }

    }

}
