/*
 * Data Streaming - OpenAPI
 *
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using data_streaming.Model;
using data_streaming.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace data_streaming.Test.Model
{
    /// <summary>
    ///  Class for testing CustomDataStreamingPostBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomDataStreamingPostBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomDataStreamingPostBody
        //private CustomDataStreamingPostBody instance;

        public CustomDataStreamingPostBodyTests()
        {
            // TODO uncomment below to create an instance of CustomDataStreamingPostBody
            //instance = new CustomDataStreamingPostBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomDataStreamingPostBody
        /// </summary>
        [Fact]
        public void CustomDataStreamingPostBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomDataStreamingPostBody
            //Assert.IsType<CustomDataStreamingPostBody>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DataSource'
        /// </summary>
        [Fact]
        public void DataSourceTest()
        {
            // TODO unit test for the property 'DataSource'
        }
        /// <summary>
        /// Test the property 'TemplateModel'
        /// </summary>
        [Fact]
        public void TemplateModelTest()
        {
            // TODO unit test for the property 'TemplateModel'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

    }

}
