/*
 * Data Streaming - OpenAPI
 *
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using data_streaming.Model;
using data_streaming.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace data_streaming.Test.Model
{
    /// <summary>
    ///  Class for testing DataStreamingsDomainResponseLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataStreamingsDomainResponseLinksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataStreamingsDomainResponseLinks
        //private DataStreamingsDomainResponseLinks instance;

        public DataStreamingsDomainResponseLinksTests()
        {
            // TODO uncomment below to create an instance of DataStreamingsDomainResponseLinks
            //instance = new DataStreamingsDomainResponseLinks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataStreamingsDomainResponseLinks
        /// </summary>
        [Fact]
        public void DataStreamingsDomainResponseLinksInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataStreamingsDomainResponseLinks
            //Assert.IsType<DataStreamingsDomainResponseLinks>(instance);
        }


        /// <summary>
        /// Test the property 'Previous'
        /// </summary>
        [Fact]
        public void PreviousTest()
        {
            // TODO unit test for the property 'Previous'
        }
        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Fact]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }

    }

}
