/*
 * Data Streaming - OpenAPI
 *
 * The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using data_streaming.Model;
using data_streaming.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace data_streaming.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateResultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateResults
        //private TemplateResults instance;

        public TemplateResultsTests()
        {
            // TODO uncomment below to create an instance of TemplateResults
            //instance = new TemplateResults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateResults
        /// </summary>
        [Fact]
        public void TemplateResultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateResults
            //Assert.IsType<TemplateResults>(instance);
        }


        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'SchemaVersion'
        /// </summary>
        [Fact]
        public void SchemaVersionTest()
        {
            // TODO unit test for the property 'SchemaVersion'
        }

    }

}
