/*
 * Edge Function
 *
 * Azion Edge Function API
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using edgefunctions.Model;
using edgefunctions.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace edgefunctions.Test.Model
{
    /// <summary>
    ///  Class for testing PutEdgeFunctionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PutEdgeFunctionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PutEdgeFunctionRequest
        //private PutEdgeFunctionRequest instance;

        public PutEdgeFunctionRequestTests()
        {
            // TODO uncomment below to create an instance of PutEdgeFunctionRequest
            //instance = new PutEdgeFunctionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PutEdgeFunctionRequest
        /// </summary>
        [Fact]
        public void PutEdgeFunctionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PutEdgeFunctionRequest
            //Assert.IsType<PutEdgeFunctionRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'JsonArgs'
        /// </summary>
        [Fact]
        public void JsonArgsTest()
        {
            // TODO unit test for the property 'JsonArgs'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'InitiatorType'
        /// </summary>
        [Fact]
        public void InitiatorTypeTest()
        {
            // TODO unit test for the property 'InitiatorType'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

    }

}
