/*
 * Azion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using networklist.Model;
using networklist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace networklist.Test.Model
{
    /// <summary>
    ///  Class for testing ListNetworkListsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListNetworkListsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListNetworkListsResponse
        //private ListNetworkListsResponse instance;

        public ListNetworkListsResponseTests()
        {
            // TODO uncomment below to create an instance of ListNetworkListsResponse
            //instance = new ListNetworkListsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListNetworkListsResponse
        /// </summary>
        [Fact]
        public void ListNetworkListsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListNetworkListsResponse
            //Assert.IsType<ListNetworkListsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }
        /// <summary>
        /// Test the property 'SchemaVersion'
        /// </summary>
        [Fact]
        public void SchemaVersionTest()
        {
            // TODO unit test for the property 'SchemaVersion'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
